version: "3"
volumes:
  jenkins-home:
    driver: "local"
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    ports:
      - "18080:8080"
      - "50000:50000"
    restart: "always"
    volumes:
      - "jenkins-home:/var/jenkins_home"